'use client';
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/ironman.png" style={{width: "16px", height: "16px", borderRadius: "50%"}}/>
        <title>Yun Boyloy</title>
      </head>
      <body
        className="min-h-screen flex flex-col bg-sky-600"
      >
          <SessionProvider>
          <header className="w-full bg-white shadow-md">
            <Navbar />
          </header>
          <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8">
            {children}
            </main>
          <footer className="w-full bg-gray-500 text-center py-6 text-white">
            <Footer />
            <p>© 2025 Yun Boyloy. All Rights Reserved.</p>
          </footer>
          </SessionProvider>
  
      </body>
    </html>
  );
}
